### ISSUE TITLE
Config() Issues

### ISSUE THREAD

**Issue by developer11092** [vitorfs/woid#4]
Hello @vitorfs!
I am new to github as well as in django, I cloned your project to further understand it but there seems to be an error as when I execute the command runserver it gives an error that the config does not exist or the values are not provided for certain thongs such as API's, Database url and etc,
Need some guidance!

**Comment by cs-ark** [comment]
what exactly is the error? log please

**Comment by kaleumakant** [comment]
I am also getting same errors.

raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: DATABASE_URL option not found and default value was not defined.

**Comment by soungrong** [comment]
@developer11092 @kaleumakant 

You're probably missing a **.env** a.k.a. environment variables file in the project root DIR, that has those values defined. If you refer to **.env.example** that's part of this repo, you'll find samples of some of the keys (e.g. SECRET_KEY) and values (e.g. s3cr3tk3y) that need to be defined.

So in short, you need to create a new file called .env, copy the samples from .env.example and then fill in the missing key/value pair errors as it occurs when you run the runserver command.

For DATABASE_URL specifically, you can refer to the **URL schema** section on this page https://github.com/kennethreitz/dj-database-url for what it should look like

After that you'll probably get another error where "NYTIMES_API_KEY" is missing. So you'll need to either comment out that line in **settings.py** to get the runserver command to work, or acquire the relevant API key and fill it in to your **.env** file.
